### ISSUE TITLE
missing capability checks in externallib functions.

### ISSUE THREAD

**Issue by danmarsden** [SE-Stuttgart/moodle-block_booksearch#7]
please add context/capability checks to make sure the user calling the webservice is allowed to access the course being passed.

more info:
https://moodledev.io/docs/apis/subsystems/external/writing-a-service#context-and-capability-checks

**Comment by MakinZeel** [comment]
We now demand courseid and userid for all webservice requests.
We then check both for validity and if the given user is allowed to access the course content using the can_access_course function.
Additionally we have a course context validity check.
